### ISSUE TITLE
sorry to make an issue but i need an answer

### ISSUE THREAD

**Issue by fnfporterhi** [SanicBTW/SancoWS#1]
did memehoovy leave github? i got the 404 on his acc.

**Comment by SanicBTW** [comment]
apparently his account got suspended or something

**Comment by SanicBTW** [comment]
i just couldnt see his account at all cuz he blocked me

**Comment by SanicBTW** [comment]
he said that it got flagged

**Comment by SanicBTW** [comment]
![image](https://user-images.githubusercontent.com/58010536/212419485-a574ba6e-005e-4ca4-b6a2-1fb1132486ef.png)

**Comment by fnfporterhi** [comment]
MAN.

**Comment by fnfporterhi** [comment]
is he creating a new one?

**Comment by fnfporterhi** [comment]
still don’t know why he got flagged, but it’s fine i guess we can wait until he gets back 


meanwhile i’m closing this
